### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by jdonaldson10** [aspnet/jquery-ajax-unobtrusive#11]
Any change of getting this published to NPM?

Similarly to how jquery-validation-unobtrusive was updated to support this
https://github.com/aspnet/jquery-validation-unobtrusive/issues/7

**Comment by Eilon** [comment]
No idea why we didn't already do this! Must've just forgotten...

**Comment by kichalla** [comment]
https://www.npmjs.com/package/jquery-ajax-unobtrusive

**Comment by jdonaldson10** [comment]
Thanks!
