### ISSUE TITLE
Ajax redirect update

### ISSUE THREAD

**Issue by RoySalisbury** [aspnet/jquery-ajax-unobtrusive#19]
I like using ajax for my form submissions.  It allows me to update the page with the result for a nice user experience.

However, sometimes you need to redirect to a new location and not just update the existing page.   In the past in my own ajax calls I used to "unofficial" status code of "278" for this.  This has been used for about 4 years in the community.  Its a "success" code so the browsers don't try to handle it.   Adding this functionality into the unobtrusive library is pretty simple.

In the "asyncRequest" method, I just updated the "success" function to:

    success: function (data, status, xhr) {
        if (xhr.status === 278)
        {
            var location = xhr.getResponseHeader("Location") || window.location.href;
            window.location.replace(location);

            return;
        }
        asyncOnSuccess(element, data, xhr.getResponseHeader("Content-Type") || "text/html");
        getFunction(element.getAttribute("data-ajax-success"), ["data", "status", "xhr"]).apply(element, arguments);
    },

Then you just have to return a status code 278 with a "Location" header containing the Url of the redirect.  Works great.  

Might be worth adding to the base library.

A second options (that requires no library update) is to return a "278" status code, with the "Location" header, but ALSO set the "Content-Type" to "application/x-javascript".  The library has a check for this in the "asyncOnSuccess" and will NOT run the "success" logic.  But it WILL run the "data-ajax-complete" method.  Then you can add your own status code "278" check and do the redirect.

I like the first option .. seems cleaner.

**Comment by Eilon** [comment]
Hi, this is an interesting feature request but given that it depends on non-standard behavior we feel it is not a good fit for the framework.
