### ISSUE TITLE
Consider restricting the contentType of the data that will get inserted/replaced when data-ajax-update is declared

### ISSUE THREAD

**Issue by mkasperski** [aspnet/jquery-ajax-unobtrusive#2]
Currently, upon successful ajax call, the library calls ```asyncOnSuccess``` method, which, if ```data-ajax-update``` attribute is set, will update (or replace, or add before/after) the target specified in this attribute with the returned data from the call. The update happens regardless if the data is html or not (the only check is done for it being a javascript content). So in case of, for example, contentType of ```application/json``` or binary data, it will still be treated like html.

This behavior makes implementing server responses that return different contentType depending on the form request impossible, because each response will get inserted into html. The ```asyncOnSuccess``` method is also called unconditionally, before user-defined success callback is called and thus it's impossible to override. One could argue that this can be avoided by not specifying the ```data-ajax-update``` attribute in the first place, but this attribute gets declared statically, in design time, while the contentType of the response may be set dynamically by the server, eg. return ```text/html``` if the form had validation errors (this would replace the form content, in which case the attribute is needed) or return ```application/json``` with processing data for javascript code if the post was successful (in which case the html update should be skipped).

My proposal is to check the data's contentType if it's ```text/html``` and only then manipulate the html. This would still be within the intent of your library to handle html updates, but will be constrained to content that is in fact updateable. (It might be also considered to allow ```text/plain``` to be handled as well, although in this case I'd suggest using ```$.text()``` instead of ```$.html()``` when doing the manipulation).

What do you think about it?

**Comment by danroth27** [comment]
We think there are too many cases were non-html content might actually be valid and used (you already mention the text/plain case). Given that this behavior has already shipped we don't want to risk breaking existing users. For your specific use case you might consider using a modified copy of the library that suits your needs.
