### ISSUE TITLE
Any docs for the lib?

### ISSUE THREAD

**Issue by thiagomajesk** [aspnet/jquery-ajax-unobtrusive#24]
Is there any docs/sample code for the lib using asp.net core? Maybe someone could provide a small README or a dedicated chapter on the wiki.

**Comment by garfbradaz** [comment]
Did you find any docs?

**Comment by thiagomajesk** [comment]
@garfbradaz Unfortunately not, but you can grasp some basic concepts for prior versions with aspnet mvc (check on stackoverflow) and by looking at the source code.

If it is any help, I'm using it like this in my forms:

`data-ajax="true" data-ajax-method="post" data-ajax-mode="replace" data-ajax-update="{element-id}"`

**Comment by os1r1s110** [comment]
First things first it's good to read the official documentation: http://api.jquery.com/jquery.ajax/
Then, you can better understand what this wrapper does for you and to know how to use it, maybe this link can help: https://stackoverflow.com/a/35362280/3365147

**Comment by mkArtakMSFT** [comment]
Hi @thiagomajesk. We plan to address this issue as part of the following issue: https://github.com/aspnet/Docs/issues/1111 
Closing this issue as a dupe.
