### ISSUE TITLE
cdn

### ISSUE THREAD

**Issue by rm2k** [aspnet/jquery-ajax-unobtrusive#25]
do we have cdn-hosted copy of this library?

**Comment by MartinKolarik** [comment]
I'm probably a little late here, but it's hosted at jsDelivr: https://www.jsdelivr.com/package/npm/jquery-ajax-unobtrusive

**Comment by mkArtakMSFT** [comment]
Hi @rm2k. You can use https://docs.microsoft.com/en-us/aspnet/ajax/cdn/overview#ASPNET_MVC_Releases_on_the_CDN_16 to find where the libraries are hosted. Hope this helps.
