### ISSUE TITLE
Add the easy ability to not autogenerate X-Requested-With and _ for GET requests

### ISSUE THREAD

**Issue by zippy1981** [aspnet/jquery-ajax-unobtrusive#27]
[Here is my example fiddle illustrating this](https://jsfiddle.net/r59shfjo/2/).

I want to consume FIPS block data from the census bureau. The URL should look like:

https://data.fcc.gov/api/block/find?showall=true&latitude=40.6590165&longitude=-74.2896593

However, if I use unobtrusive ajax on a GET form, it adds two paramaters, `_` and `X-Requested-With` I get blocked like so:

![image](https://user-images.githubusercontent.com/146930/30675650-aeea3bf4-9e4f-11e7-9ec3-9f27b077f0e9.png)

I'd like a nicer method than [removing it after its added with BeginForm](https://stackoverflow.com/questions/37104176/remove-x-requested-with-from-query-string-url-during-ajax-request). as discussed here.

**Comment by Eilon** [comment]
Are you using Unobtrusive AJAX to call a site other than your own? It's really meant only for calling back to your own site - I can't say we considered scenarios for calling other sites.

I recommend using the relatively simple [jQuery APIs](https://api.jquery.com/jQuery.ajax/) for this (if you're already using jQuery), or using the [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) API, or the [Request library](https://github.com/request/request#super-simple-to-use).
