### ISSUE TITLE
Scripts are not evaluated using data-ajax-mode="before" or data-ajax-mode="after"

### ISSUE THREAD

**Issue by San4es** [aspnet/jquery-ajax-unobtrusive#29]
When I use `@Ajax.ActionLink` with `InsertionMode = InsertionMode.InsertAfter` or  `InsertionMode = InsertionMode.InsertAfter` to load `PartialView`, script tags loaded from the server are not evaluated (but with `InsertionMode = InsertionMode.Replace` and `InsertionMode = InsertionMode.ReplaceWith` scripts are evaluated).

It happens because the native DOM API (not jQuery) is used in this code block:
https://github.com/aspnet/jquery-ajax-unobtrusive/blob/master/src/jquery.unobtrusive-ajax.js#L57-L68

I suggest fixing this scenario using a jQuery API for the `data-ajax-mode="before"` and `data-ajax-mode="after"` modes.

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb, can you please look into this?
/cc: @danroth27, @SteveSandersonMS FYI

**Comment by InhouseMedia** [comment]
can you please look into this?

**Comment by ajaybhargavb** [comment]
4269c0f874836ace88810e645a82fa9ca75697e9
