### ISSUE TITLE
Disable proxy safe override

### ISSUE THREAD

**Issue by mguinness** [aspnet/jquery-ajax-unobtrusive#33]
The `isMethodProxySafe` function limits methods to GET or POST.  Is it possible to add PUT, PATCH and DELETE to allow REST support?

If not, can you add support for an attribute named `data-ajax-method-override`?  It would default to true, but could be set to false to ignore.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us @mguinness. We don't plan to expand functionality of this library any further. The only changes we consider are critical bug fixes.
