### ISSUE TITLE
Update NPM Package

### ISSUE THREAD

**Issue by InhouseMedia** [aspnet/jquery-ajax-unobtrusive#35]
Could you please update this package also on NPM to the latest version?
Kind regards

**Comment by Eilon** [comment]
I don't think we were planning to update the NPM package at https://www.npmjs.com/package/jquery-ajax-unobtrusive because this library is rarely used with NPM. This library is mostly used as a NuGet package or via a CDN.

@InhouseMedia - can you tell us more about your app? Is it using MVC 5.x, or using ASP.NET Core, or something else entirely?

**Comment by XelaNimed** [comment]
@InhouseMedia you can use jsdelivr like so:
https://cdn.jsdelivr.net/gh/aspnet/jquery-ajax-unobtrusive@3.2.5/dist/jquery.unobtrusive-ajax.min.js

**Comment by harmonmi** [comment]
Would love to keep it updated on NPM as well!

**Comment by mkArtakMSFT** [comment]
The number of folks looking for this package on npm is so low, that its not worth the investment. Consider retrieving the package from AjaxCDN as an alternative: https://ajax.aspnetcdn.com/ajax/jquery.unobtrusive-ajax/3.2.5/jquery.unobtrusive-ajax.min.js

**Comment by GerkinDev** [comment]
Hi,

Microsoft tends to talk about automation about everything. Hey guys, its easy to auto-release an npm package with a CI tool I guess you already have. And some CDNs (such as CDNJS) provide only versions published on NPM.

I guess I'll do a PR.

**Comment by iMusashi** [comment]
I would +1 @GerkinDev, this file is important for client side development and used to be referenced earlier in a different way using Bower. However, now that Bower is removing their support, .NET users will be using Library Manager, a Visual Studio built-in tool that allows users to manager client side libraries and it references cdnjs as a standard cdn server. 

I hope, this file is added to the list, thanks.

**Comment by ejcortes** [comment]
+1
