### ISSUE TITLE
Could use a good working sample and step by step instructions

### ISSUE THREAD

**Issue by psijkof** [aspnet/jquery-ajax-unobtrusive#39]
Hello,

Great lib, great promise, but hard to implement without proper guidance.

We ran into issues, and would love to resolve this.

https://stackoverflow.com/questions/51059649/unobtrusive-ajax-lib-not-sending-xmlhttprequest-header

Thanks.

**Comment by psijkof** [comment]
The repo I've made shows a good working sample for ASP.NET Core Razor Pages.

https://github.com/psijkof/RazorPagesAjax

**Comment by mkArtakMSFT** [comment]
Hi @psijkof. 
Sorry for our late response. Did you get the answer to your question?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner. Hopefully you've figured out a solution to your problem. If you have more details and are encountering this issue please add a new reply and re-open the issue.
