### ISSUE TITLE
data-ajax-begin function should include the settings like jQuery beforeSend

### ISSUE THREAD

**Issue by mmiller678** [aspnet/jquery-ajax-unobtrusive#7]
When specifying a function for the data-ajax-begin only the xhr parameter is passed.  The settings parameter should also be included to match the jQuery beforeSend.  This would allow changes to the data, url, etc. prior to the request being made.   This should be a non-breaking change.

**Comment by mkArtakMSFT** [comment]
Closing this as we've seen not much interest from the community for this change.
